#!/usr/bin/env node
// Aggregates data/media.json5 (the unified D1 cartridge catalogue) into
// runtime artifacts:
//
//   - data/media.json — plain JSON, the published artifact loaded by
//     downstream tooling.
//   - src/media.generated.ts — typed re-export consumed by `media.ts`.
//
// Each entry's `key` (UPPER_SNAKE_CASE constant) is auto-derived from
// `material` + `text` + `background` + `tapeWidthMm` — the JSON5
// source-of-truth doesn't repeat it. Validation: required fields,
// unique `id`, `targetModels` ∈ {d1, d1-wide, d1-24}, derived `key`
// uniqueness.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import JSON5 from 'json5';

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const PKG_ROOT = resolve(SCRIPT_DIR, '..');
const MEDIA_FILE = resolve(PKG_ROOT, 'data/media.json5');
const MEDIA_OUT = resolve(PKG_ROOT, 'data/media.json');
const MEDIA_TS = resolve(PKG_ROOT, 'src/media.generated.ts');

const VALID_TARGET_MODELS = new Set(['d1', 'd1-wide', 'd1-24']);
const REQUIRED_FIELDS = [
  'id',
  'name',
  'type',
  'widthMm',
  'tapeWidthMm',
  'material',
  'text',
  'background',
  'printableDots',
  'bytesPerLine',
  'targetModels',
];

const errors = [];
const fail = msg => errors.push(msg);

function deriveKey(entry) {
  const material = String(entry.material).replace(/-/g, '_').toUpperCase();
  const text = String(entry.text).replace(/-/g, '_').toUpperCase();
  const background = String(entry.background).replace(/-/g, '_').toUpperCase();
  return `${material}_${text}_ON_${background}_${entry.tapeWidthMm}`;
}

function loadMedia() {
  const entries = JSON5.parse(readFileSync(MEDIA_FILE, 'utf8'));
  if (!Array.isArray(entries)) {
    fail('media.json5: top-level must be an array');
    return [];
  }
  const seenIds = new Set();
  const seenKeys = new Set();
  const out = [];
  for (const [i, m] of entries.entries()) {
    const where = `media[${i}]${m?.id ? ` (${m.id})` : ''}`;
    for (const f of REQUIRED_FIELDS) {
      if (m?.[f] === undefined) fail(`${where}: missing \`${f}\``);
    }
    if (m?.type !== 'tape') fail(`${where}: type must be "tape"`);
    if (typeof m?.id !== 'string') fail(`${where}: id must be a string`);
    else if (seenIds.has(m.id)) fail(`${where}: duplicate id "${m.id}"`);
    else seenIds.add(m.id);
    if (Array.isArray(m?.targetModels)) {
      for (const t of m.targetModels) {
        if (!VALID_TARGET_MODELS.has(t)) {
          fail(`${where}: unknown targetModels entry "${t}" (allowed: ${[...VALID_TARGET_MODELS].join(', ')})`);
        }
      }
    } else {
      fail(`${where}: targetModels must be an array`);
    }
    if (typeof m?.printableDots === 'number' && typeof m?.bytesPerLine === 'number') {
      const expected = Math.ceil(m.printableDots / 8);
      if (m.bytesPerLine !== expected) {
        fail(
          `${where}: bytesPerLine ${m.bytesPerLine} ≠ ceil(printableDots/8) = ${expected}`,
        );
      }
    }
    const key = deriveKey(m);
    if (seenKeys.has(key)) {
      fail(`${where}: derived key "${key}" collides with an earlier entry`);
    } else {
      seenKeys.add(key);
    }
    out.push({ key, ...m });
  }
  return out;
}

const media = loadMedia();

if (errors.length > 0) {
  console.error(`[compile-data] ${errors.length} error(s):`);
  for (const e of errors) console.error('  - ' + e);
  process.exit(1);
}

mkdirSync(dirname(MEDIA_OUT), { recursive: true });
// `key` is included in the JSON projection so cross-repo consumers
// (labelmanager / labelwriter compile scripts) can build their typed
// keyed registries without re-deriving it.
writeFileSync(MEDIA_OUT, JSON.stringify({ schemaVersion: 1, media }, null, 2) + '\n');

function emitMediaEntry(entry) {
  const { key: _key, ...rest } = entry;
  const inner = JSON.stringify(rest, null, 2).replace(/\n/g, '\n  ');
  return `  ${entry.key}: ${inner},`;
}
const mediaEntriesObj = media.map(emitMediaEntry).join('\n');
const mediaKeyUnion = media.map(m => `'${m.key}'`).join(' | ');
const mediaTs = `// AUTO-GENERATED by scripts/compile-data.mjs from data/media.json5.
// Edit that file, not this one. Run \`pnpm run compile-data\`.

import type { D1Media } from './types.js';

export type D1MediaKey = ${mediaKeyUnion};

export const D1_MEDIA = {
${mediaEntriesObj}
} as const satisfies Record<D1MediaKey, D1Media>;

export const D1_MEDIA_LIST: readonly D1Media[] = Object.values(D1_MEDIA);
`;
mkdirSync(dirname(MEDIA_TS), { recursive: true });
writeFileSync(MEDIA_TS, mediaTs);

console.log(`[compile-data] OK — ${media.length} D1 media entries → data/media.json, src/media.generated.ts`);
